name: Build Web Application Server and release
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout source
      - uses: actions/checkout@v2
      # install jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # setup settings.xml of maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/atlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      # packaging project
      - name: Build with Maven
        run: mvn -P tomcat9 -B package --file pom.xml
      # get project version
      - name: Bump Version
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}
      - name: git push
        run: |
          rm -rf /tmp/tomcat-test
          mkdir -p /tmp/tomcat-test
          git clone https://github.com/ATLENA/lat-engine.git /tmp/tomcat-temp
          git config --global user.email "seosej@gmail.com"
          git config --global user.name "seosej"
          mkdir -p /tmp/tomcat-temp/tomcat
          cp -rf was-dist/target/tomcat/* /tmp/tomcat-temp/tomcat/      
          cd /tmp/tomcat-temp && git add . && git commit -a -m "Pushed from lat-tomcat" && git push
